import React from "react";
import SectionCard from "../../shared/layout/SectionCard";
import StatCard from "../../shared/data-display/StatCard";

import {
  ResponsiveContainer,
  LineChart,
  CartesianGrid,
  XAxis,
  YAxis,
  Tooltip,
  Line,
  BarChart,
  Bar,
} from "recharts";

export interface DashboardKpis {
  totalJobs: number;
  totalRevenue: number;
  cancellationsRate: number;
  companiesIn: number;
  companiesOut: number;
}

const jobsTrendData = [
  { label: "Mon", jobs: 120, cancellations: 5 },
  { label: "Tue", jobs: 134, cancellations: 4 },
  { label: "Wed", jobs: 110, cancellations: 7 },
  { label: "Thu", jobs: 145, cancellations: 3 },
  { label: "Fri", jobs: 160, cancellations: 6 },
  { label: "Sat", jobs: 98, cancellations: 2 },
  { label: "Sun", jobs: 75, cancellations: 4 },
];

const revenueTrendData = [
  { label: "Week 1", revenue: 3200 },
  { label: "Week 2", revenue: 3800 },
  { label: "Week 3", revenue: 4100 },
  { label: "Week 4", revenue: 3650 },
];

interface DashboardChartsSectionProps {
  kpis: DashboardKpis;
  rangeLabel?: string;
}

const DashboardChartsSection: React.FC<DashboardChartsSectionProps> = ({
  kpis,
  rangeLabel,
}) => {
  return (
    <>
      {/* KPI row */}
      <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
        <StatCard
          label="Total Jobs"
          value={kpis.totalJobs}
          subLabel={
            rangeLabel
              ? `Jobs completed in selected period (${rangeLabel})`
              : "Jobs completed in selected period"
          }
        />
        <StatCard
          label="Total Revenue"
          value={`$${kpis.totalRevenue.toLocaleString()}`}
          subLabel="All locksmith jobs"
        />
        <StatCard
          label="Cancellation Rate"
          value={`${kpis.cancellationsRate.toFixed(1)}%`}
          subLabel="Across all jobs"
        />
        <StatCard
          label="Companies IN / OUT"
          value={`${kpis.companiesIn} / ${kpis.companiesOut}`}
          subLabel="Net company movement"
        />
      </section>

      {/* Charts */}
      <section className="grid gap-4 lg:grid-cols-2">
        <SectionCard
          title="Jobs & cancellations trend"
          description="Volume and cancellations across the selected period."
          className="min-w-0"
        >
          <div className="h-64 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={jobsTrendData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#E5E7EB" />
                <XAxis
                  dataKey="label"
                  tick={{ fontSize: 11 }}
                  axisLine={false}
                  tickLine={false}
                />
                <YAxis
                  tick={{ fontSize: 11 }}
                  axisLine={false}
                  tickLine={false}
                />
                <Tooltip />
                <Line
                  type="monotone"
                  dataKey="jobs"
                  stroke="#2563EB"
                  strokeWidth={2}
                  dot={false}
                  name="Jobs"
                />
                <Line
                  type="monotone"
                  dataKey="cancellations"
                  stroke="#EF4444"
                  strokeWidth={2}
                  dot={false}
                  name="Cancellations"
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </SectionCard>

        <SectionCard
          title="Revenue trend"
          description="Weekly revenue generated by locksmith jobs."
          className="min-w-0"
        >
          <div className="h-64 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={revenueTrendData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#E5E7EB" />
                <XAxis
                  dataKey="label"
                  tick={{ fontSize: 11 }}
                  axisLine={false}
                  tickLine={false}
                />
                <YAxis
                  tick={{ fontSize: 11 }}
                  axisLine={false}
                  tickLine={false}
                />
                <Tooltip />
                <Bar dataKey="revenue" fill="#10B981" name="Revenue" />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </SectionCard>
      </section>
    </>
  );
};

export default DashboardChartsSection;
